# typed: false
# frozen_string_literal: true

# This file was generated by Aten Security release automation. DO NOT EDIT.
class Thoth < Formula
  desc "Thoth MCP governance runtime and headless control-plane CLI"
  homepage "https://github.com/atensecurity/thoth"
  version "0.3.7"
  url "https://github.com/atensecurity/thoth/releases/download/v0.3.7/thoth-macos-universal.tar.gz"
  sha256 "bc2c8de4342519f0d5696ada0417dc6c2a0968aca988aaebad04550a915e67ab"
  depends_on :macos

  def install
    if File.exist?("bin/thoth") && File.exist?("bin/thothctl")
      bin.install "bin/thoth", "bin/thothctl"
    elsif File.exist?("thoth") && File.exist?("thothctl")
      bin.install "thoth", "thothctl"
    else
      odie "Could not find thoth binaries in archive root or bin/ directory"
    end
  end

  def caveats
    <<~EOS
      Installed binaries:
        - thoth
        - thothctl

      Quick start:
        thoth --help
        thothctl --help
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/thoth --version")
    assert_match version.to_s, shell_output("#{bin}/thothctl --version")
  end
end
